name: CI

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11]
        node-version: [18]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install and test frontend
      run: |
        if [ -f "package.json" ] && [ "$(jq -r '.dependencies | length' package.json)" -gt 0 ] || [ "$(jq -r '.devDependencies | length' package.json)" -gt 0 ]; then
          npm ci
          npm run lint
          npm run test
        else
          echo "No frontend dependencies found, skipping frontend tests"
        fi
    
    - name: Install and test backend
      run: |
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
          pip install -e .
          pytest
        else
          echo "No requirements.txt found, skipping backend tests"
        fi 